blank_issues_enabled: false
contact_links:
  - name: Community Support
    url: https://github.com/foxminchan/HutechCanteen/discussions
    about: Please ask and answer questions here.
  - name: Security Bug Bounty
    url: https://github.com/foxminchan/HutechCanteen/security/advisories
    about: Please report security vulnerabilities here.