version: "3.9"

services:
  api:
    image: ghcr.io/foxminchan/rent-car-api:latest
    container_name: api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - db
    networks:
      - bridge-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/hc"]
      interval: 10s
      timeout: 5s
      retries: 3

  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rent-car
    volumes:
      - ./db-data:/var/lib/postgresql/data
    networks:
      - bridge-network

networks:
  bridge-network:
    driver: bridge

volumes:
  db-data:
